### ISSUE TITLE
Initialise a flutter project (Use stable channel)

### ISSUE THREAD

**Issue by vip-2812** [vip-2812/ecommerce-flutter#1]
Just initialise a flutter project and create a pull request. 
Use stable channel of flutter and latest version so that it will be easier for other contributors to contribute.

Post your doubt here:[Discord server]( https://discord.gg/yxPakE)

**Comment by abhikhedekar4241** [comment]
I would like to do it. Please assign me.

**Comment by vip-2812** [comment]
I will assign it to you. Follow the instructions.
