### ISSUE TITLE
Create proper file structure for whole project.

### ISSUE THREAD

**Issue by vip-2812** [vip-2812/ecommerce-flutter#10]
Create proper file structure for whole project.
Project info:
1. It is an a-commerce application similar to other platforms.
2. We have to strictly follow BLoC pattern. 

Post your doubt here:[Discord server]( https://discord.gg/yxPakE)

**Comment by abhikhedekar4241** [comment]
Please assign this to me. I have experience in BLoC pattern. I will create it ASAP.

**Comment by vip-2812** [comment]
I have assigned you. Do follow the instructions. And join discord server if you have any doubts.
